spring:
  cloud:
    stream:
      bindings:
        customer-input-channel:
          destination: Customer
        balance-input-channel:
          destination: Balance
        customerBalance-output-channel:
          destination: CustomerBalance
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
          bindings:
            customer-input-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            balance-input-channel:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            customerBalance-output-channel:
              producer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde